### ISSUE TITLE
Libssh

### ISSUE THREAD

**Issue by lukestanley** [NodeTrie/NodeTrie_Py#1]
Hi, I thought you might need to see this:
https://www.libssh.org/2018/10/16/libssh-0-8-4-and-0-7-6-security-and-bugfix-release/

@pkittenis

**Comment by pkittenis** [comment]
Hi,

Thanks for the interest, though:

a) This is an unrelated repository to [ssh-python](https://github.com/ParallelSSH/ssh-python) which I presume is what is wanted.
b) That vulnerability is for libssh _server_ implementation for which bindings are not provided (no interest in doing so either). It does not affect clients.
